### ISSUE TITLE
Usage documentation is missing

### ISSUE THREAD

**Issue by markstos** [VolantisDev/node-systemctl#2]
This module lacks basic usage documentation.

Documentation was contributed in #1 along with some other changes, but no version of it was ever merged.

**Comment by ReplicaObscura** [comment]
Thanks for your comment!

#1 is not ready for merging (See the comments there) as it includes several unrelated changes. The documentation in #1 also wouldn't make sense to merge by itself, because it doesn't apply to the current version of the module.

If you're interested in helping out, the changes from PR #1 could fairly easily be split out to separate PRs so that the main funcitonality change and documentation could be merged in without things like the license change having to be merged at the same time. Or documentation could be committed separately for the current version and updated once the changes from #1 are ready to merge.

Otherwise, I plan to cherry pick some of the commits from #1 very soon, along with adding compatibility with the existing version back in, so documentation will be available at that time.

**Comment by ReplicaObscura** [comment]
Basic usage documentation added based somewhat on the documentation proposed in #1. Feel free to contribute further to the documentation if you're able and willing!
